<?php
/*
 * Pterodactyl Panel 0.7.19  Bulgarian translation
 * Author: Kaloian Penchev (admin@kaloianpenchev.eu)
 * License: Free to use
 * Donate:
 *      PayPal: https://paypal.me/kalchobratme
 */

return [
    'email' => 'Имейл',
    'user_identifier' => 'Потребителско име и имейл',
    'password' => 'Парола',
    'confirm_password' => 'Потвърдете паролата',
    'login' => 'Вход',
    'home' => 'Вкъщи',
    'servers' => 'Сървъри',
    'id' => 'ИД',
    'name' => 'Име',
    'node' => 'Node',
    'connection' => 'Връзка',
    'memory' => 'Памет',
    'cpu' => 'Процесор',
    'disk' => 'Диск',
    'status' => 'Статус',
    'search' => 'Търсене',
    'suspended' => 'Преустановен',
    'account' => 'Акаунт',
    'security' => 'Сигурност',
    'ip' => 'IP Адрес',
    'last_activity' => 'Последна активност',
    'revoke' => 'Отхвърлям',
    '2fa_token' => 'Токен за удостоверение',
    'submit' => 'Приложете',
    'close' => 'Затворете',
    'settings' => 'Настройки',
    'configuration' => 'Конфигурация',
    'sftp' => 'SFTP',
    'databases' => 'Бази данни',
    'memo' => 'Мемо',
    'created' => 'Създаден',
    'expires' => 'Изтича',
    'public_key' => 'Токен',
    'api_access' => 'API Достъп',
    'never' => 'никога',
    'sign_out' => 'Изход',
    'admin_control' => 'Админ контрол',
    'required' => 'Задължително',
    'port' => 'Порт',
    'username' => 'Потребител',
    'database' => 'База данни',
    'new' => 'Нов',
    'danger' => 'Опасност',
    'create' => 'Създайте',
    'select_all' => 'Изберете всички',
    'select_none' => 'Не избирай никое',
    'alias' => 'Alias',
    'primary' => 'Основен',
    'make_primary' => 'Направи основен',
    'none' => 'Никое',
    'cancel' => 'Откажи',
    'created_at' => 'Създаден на',
    'action' => 'Действие',
    'data' => 'Дата',
    'queued' => 'Опашка',
    'last_run' => 'Последно изпълнен',
    'next_run' => 'Следващо изпълнение',
    'not_run_yet' => 'Още не е изпълнявана',
    'yes' => 'Да',
    'no' => 'Не',
    'delete' => 'Изтрийте',
    '2fa' => '2ФА',
    'logout' => 'Изход',
    'admin_cp' => 'Админ контрол панел',
    'optional' => 'По желание',
    'read_only' => 'Само Четене',
    'relation' => 'Връзка',
    'owner' => 'Собственик',
    'admin' => 'Администратор',
    'subuser' => 'Подпотребител',
    'captcha_invalid' => 'Предоставената Captcha е невалидна.',
    'tasks' => 'Задачи',
    'seconds' => 'Секунди',
    'minutes' => 'Минути',
    'under_maintenance' => 'В режим на поддръжка',
    'days' => [
        'sun' => 'Неделя',
        'mon' => 'Понеделник',
        'tues' => 'Вторник',
        'wed' => 'Сряда',
        'thurs' => 'Четвъртък',
        'fri' => 'Петък',
        'sat' => 'Събота',
    ],
    'last_used' => 'Последно използван',
];
